@extends('app')
@section('content')

<link rel="stylesheet" href="{{URL::asset('public/assets/css/style.css')}}">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
{{-- <link rel="stylesheet" href="{{URL::asset('public')}}/stemi_css/datepicker/jquery.datetimepicker.css">
<script src="{{URL::asset('public')}}/stemi_css/datepicker/jquery.datetimepicker.js"></script> --}}
<script type="text/javascript" src="{{URL::asset('public/stemi_js/jquery-listswipe.js')}}"></script>
<script type="text/javascript">
    $(function () {


        $('.example-2').listSwipe({
            leftAction: true,
            closeOnOpen: true,
            // itemActionWidth: 200,
            // snapDuration: 500
        });
    });

</script>

<style type="text/css">
/*

 */
 .slide-in-left{-webkit-animation:slide-in-left .5s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-left .5s cubic-bezier(.25,.46,.45,.94) both}
/* ----------------------------------------------
 * Generated by Animista on 2020-11-27 18:6:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

 @-webkit-keyframes slide-in-left{0%{-webkit-transform:translateX(-1000px);transform:translateX(-1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}@keyframes slide-in-left{0%{-webkit-transform:translateX(-1000px);transform:translateX(-1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}
/*

 */
    .item-list {
        overflow: hidden;
    }

    .item-list .item {
        position: relative;
        display: table;
        width: 100%;
        background: #FFF;
        margin-top: 5px;
    }

    .item-list .item>div {
        padding: 0 105px 0 11px;
    }

    .item-list .item .action {
        position: absolute;
        width: 80px;
        height: 100%;
        top: 0;
        border: 0;
        color: #FFF;
        outline: none;
    }

    .item-list .item .action:first-child::before,
    .item-list .item .action:last-child::before {
        position: absolute;
        top: 0;
        content: '';
        width: 2000px;
        height: 100%;
    }

    .item-list .item .action:first-child {
        left: -80px;
    }

    .item-list .item .action:first-child::before {
        right: 80px;
    }

    .item-list .item .action:last-child {
        right: -80px;
    }

    .item-list .item .action:last-child::before {
        left: 80px;
    }

    .item-list .item .action,
    .item-list .item .action::before {
        background: #ca004e;
        font-family: Kanit_ex;
        font-size: 50px;
        ;
    }

    .item-list.example-3 .action {
        width: 140px;
    }

    .item-list.example-3 .item .action:first-child {
        left: -140px;
    }

    .item-list.example-3 .item .action:first-child::before {
        right: 140px;
    }

    .item-list.example-3 .item .action:last-child {
        right: -140px;
    }

    .item-list.example-3 .item .action:last-child::before {
        left: 140px;
    }

    div#loading {
        position: fixed;
        top: 30%;
        left: 48%;
        z-index: 100000;
    }

</style>
</head>


<body>
    <style type="text/css">
        .nav-tabs .nav-item.show .nav-link,
        .nav-tabs .nav-link.active {
            color: #ffffff;
            background-color: #ca004e;
            border-color: #dee2e6 #dee2e6 #fff;
        }

        a {
            color: #000;
        }

    </style>


    <div class="col-12 text-center">
        <div id="loading">
        </div>
    </div>
    <div class="container-fulid" style="overflow: auto;
    height: 609px;">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active txt" id="send-tab" data-toggle="tab" href="#send" role="tab"
                    aria-controls="send" aria-selected="true">ส่งผู้ป่วย</a>
            </li>

            <li class="nav-item">
                <a class="nav-link  txt" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
                    aria-selected="true">รับผู้ป่วย</a>
            </li>


            <li class="nav-item">
                <a class="nav-link txt" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                    aria-controls="profile" aria-selected="false">พลาดรับ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link txt" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                    aria-controls="contact" aria-selected="false">ปฏิเสธรับ</a>
            </li>
            {{-- <li class="nav-item">
                <a class="nav-link txt" id="aml" data-toggle="tab" href="#aml" role="tab"
                    aria-controls="aml" aria-selected="false">ambulan</a>
            </li> --}}
        </ul>
        <div class="tab-content" id="myTabContent">
         
            <div class="tab-pane fade show active" id="send" role="tabpanel" aria-labelledby="send-tab">
                <div class="title-search">
                    <div class="txt-time">
                        <?php echo 'ทั้งหมด '.count($view).' รายการ';?>
                    </div>
                </div>
                <div class="card">
                    <div class="input-group mb-3" >
                        <div class="input-group-prepend">
                            <button class="btn btn-outline-secondary" type="button">
                                <i class="fa fa-search" aria-hidden="true" style="font-size: 40px;"></i>
                            </button>
                        </div>
                        <input type="text" class="form-control txt-l" placeholder="ระบุคำค้น" aria-label=""
                            aria-describedby="basic-addon1">
                    </div>

                </div>

                <div class="item-list example-2" >
                    <?php
         foreach ($view as $result) {;
               $colorCode = '';
                $delete='';
               if($result->rq_response_status == 6 || $result->rq_response_status == 7)
               {
                  $colorCode  = '#66D12E';
               }else if($result->rq_response_status == 1)
               {
                  $colorCode  = '#D3FFA0';
               }else if($result->rq_response_status == 2)
               {
                  $colorCode  = '#FFFDCC';
               }else if($result->rq_response_status == 3)
               {
                  $colorCode  = '#FF6666';
               }else if($result->rq_response_status == 4)
               {
                  $colorCode  = '#FFB266';
               }else if($result->rq_response_status == 5)
               {
                  $colorCode  = '#FEAEFA';
               }else if($result->rq_response_status == 8){
                    $delete='none;';
               }
      ?>



            <div class="item  p-section" style="background:{!!$colorCode!!}; display:{!!$delete!!} margin-top: 1rem;">
                        <div class="row">

                            {{-- <button data="{{$result->pt_id}}" id="" class="action edit"><i class="fa fa-pencil" aria-hidden="true"></i></button> --}}
                            <div class="div-img" style="text-align: center;">
                              
                                <?php if($result->pt_gender=="ไม่ระบุ" && $result->pt_picture==""){;?>
                                <img src="{{url('')}}/public/stemi_images/undefind.jpg"
                                    class="img-fluid  patent_profile" id="{{$result->pt_id}}"
                                    style="border:2px solid #ccc;    border-radius: 100%;">
                                <?php  }else if($result->pt_gender=="ชาย" && $result->pt_picture==""){;?>
                                <img src="{{url('')}}/public/stemi_images/man.jpg" class="img-fluid patent_profile"
                                    id="{{$result->pt_id}}" style="border:2px solid #ccc;    border-radius: 100%;">
                                <?php  }else if($result->pt_gender=="หญิง" && $result->pt_picture==""){;?>
                                <img src="{{url('')}}/public/stemi_images/woman.jpg" class="img-fluid patent_profile"
                                    id="{{$result->pt_id}}" style="border:2px solid #ccc;    border-radius: 100%;">
                                <?php }else if($result->pt_picture !==""){;?>

                                <img src="{{url('')}}/public/patient_pic/<?php echo $result->pt_picture;?>"
                                    class="img-fluid patent_profile" id="{{$result->pt_id}}"
                                    style="border:2px solid #ccc;    border-radius: 100%;">
                                <?php };?>
                                <a data="{{$result->pt_id}}" id="" class="edit txt-p" style="color: #2196F3;
                                    font-size: 1.5rem; text-decoration: underline solid rgb(68, 68, 68);" >Fill-in</a>
                            </div>
                            <div class="div-detail col-md-4">
                                <div class="txt-p">
                                    <?php echo  $result->pt_name;?>
                                </div>
                                <div class="txt-time">
                                    วันที่เวลาบันทึก/ส่งผู้ป่วย

                                </div>

                                <div class="txt-time">
                                    <?php echo  $result->pt_update;?>
                                </div>
                                <div class="txt-time">
                                    <?php if($result->rq_sending_status==1){;?>
                                    <i class="fa fa-ambulance" aria-hidden="true" style="font-size:50px;"></i>

                                    <?php

                     if($result->rq_response_status==1 )
                     {
                        echo "รับตัวผู้ป่วยแล้ว" ;
                     }else if($result->rq_response_status==2)
                     {
                        echo "พลาดรับ" ;
                     }else if($result->rq_response_status==3)
                     {
                        echo "ถูกปฏิเสธ ".((!empty($result->cancel_message) )?("เนื่องจาก".$result->cancel_message):"") ;
                     }else if($result->rq_response_status==4)
                     {
                        echo "ยกเลิก" ;
                     }else if($result->rq_response_status==5)
                     {
                        echo "กำลังพิจารณา EKG" ;
                     }else if($result->rq_response_status==6)
                     {
                        echo "ปิดงานระว่างทาง" ;
                     }else if($result->rq_response_status==7)
                     {
                        echo "ปิดงานส่งตัวผู้ป่วยสำเร็จ" ;
                     }else
                     {
                        echo "กำลังร้องขอ" ;
                     }

               ?>
                                    <?php  }else{;?>
                                    <i class="fa fa-file" aria-hidden="true"></i> Draft ฉบับร่าง
                                    <?php };?>

                                </div>

                            </div>
                            <div class="div-button col-4" >
                                <div>
                                    <!--<a href="{{url('')}}/patient_edit/{{$result->pt_id}}" class="btn btn-stemi btn-sm">edit</a>-->

                                    <?php if($result->rq_response_status==1 ) { ?>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <button style="margin-top:-10px;"
                                                onclick="onClickCloseJob({{$result->pt_id}})"
                                                class="btn btn-stemi-again-accept btn-sm">ปิดงาน</button>
                                        </div>
                                        <div class="col-sm-12">
                                            <button style="margin-top:5px;"
                                                id="btnPatientMap" onclick="onclickMap({{((isset($result->hos_phone))?$result->pt_id:'') }}, {{((isset($result->hos_phone))?$result->hos_phone:'') }})"
                                                class="btn btn-stemi-again-info btn-sm">ตำแหน่ง</button>
                                        </div>
                                        <div class="col-sm-1">
                                            <div style="margin-top:5px;"
                                                id="btn-stemi-shere"
                                        class="btn btn-stemi-shere btn-sm" data="{{$result->pt_id}}"><i class="fa fa-share-alt" style="color:blue; font-size:25px;"></i></div>
                                        </div>
                                    </div>
                                    <?php }else if($result->rq_response_status==2 ||
                                                $result->rq_response_status==3 ||
                                                $result->rq_response_status==4 ||
                                                $result->rq_response_status==5
                                            )
                                        { ?>

                                        <a href="{{url('')}}/patient_edit/{{$result->pt_id}}"
                                        class="btn btn-stemi-again btn-sm">ส่งตัวอีกครั้ง</a>
                                    <?php }else if($result->rq_response_status==6 || $result->rq_response_status==7) { ?>
                                        <a href="#" onclick="clickReverStatusModal({!!$result->pt_id!!})" class="btn btn-stemi-again btn-sm">ย้อนสถานะ</a>
                                    <?php } ?>

                                </div>
                            </div>
                            <button data="{{$result->rq_pt_refno}}" id="action_dels"  class="action del">ลบ</button>
                        </div>
                    </div>
                    <?php };?>
                </div>
            </div>
       
        

            <div class="tab-pane fade show" id="home" role="tabpanel" aria-labelledby="home-tab">
                <!-- รับตัวผู้ป่วย -->
                {!!$accept_list!!}

            </div>
            <div >
                <div id="doctorview">
                    {{-- {{$listdoctor}} --}}
                </div>
            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel"  aria-labelledby="profile-tab">
                <!-- พลาดรับ -->
                {!!$fail_list!!}


            </div>
            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                  <!-- ปฏิเสธ -->
                {!!isset($reject_list)  ? $reject_list : ''!!}
            </div>

            <div class="tab-pane fade" id="amllist" role="tabpanel" aria-labelledby="aml-tab">

            </div>
        </div>
    </div>
    {{-- เริ่มต้น Modal view ekg --}}
    <div id="modal_ekg" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content"  style="height: 100%;">
            <div class="modal-header">
              <h5 class="modal-title">ข้อมูล EKG</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" style="overflow: auto;">
                <p>รูปภาพ EKG</p>
                <div class="thumbs" id="ekg_pic">
             
                </div>
            <div id="btn-cofstaff" class="row">
               
            </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" id="modal_close" data-dismiss="modal_ekg">ปิด</button>
            </div>
          </div>
        </div>
    </div>
    {{-- ปิด modal ekg --}}

    <!-- Modal -->
<div class="modal fade" style="display:none;" id="modal_ambulance" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">รายชื่อ Ambulance</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="bodyambulance">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">ปิด</button>
          <button type="button" id="conf_sendpt" class="btn btn-primary">ยืนยันการส่งต่อ</button>
        </div>
      </div>
    </div>
  </div>


    <div class="modal" id="profile_data">
        <div class="modal-dialog modal-full" role="document">
            <div class="modal-content">

                <div class="modal-body">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">กลับ</button>
                    <div class="txt">ข้อมูลผู้ป่วย
                    </div>
                    <div id="profile_dis"></div>
                </div>

            </div>
        </div>
    </div>

    <div class="modal" id="editpatient">
        <div class="modal-dialog modal-full" role="document">
            <div class="modal-content">
                <div class="modal-body" id="data_patient">
                    <div class="col-12"  style="text-align: right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i></button>
                    </div>
                    <div class="" style="font-size: 200% !important;">
                        เพิ่มข้อมูล
                    </div>
                    <div class="col-12 " style="text-align: center;" id="patient_img">

                    </div>
                    <div class="col-12" style="font-size: 200% !important;">
                        ชื่อ
                        <input id="name" type="text" class="form-control  form-control-lg" placeholder="ชื่อ-นามสกุล" aria-label="Username" aria-describedby="basic-addon1">
                    </div>
                    <div class="col-12"  style="font-size: 200% !important;">
                        วัน/เดือน/ปีเกิด
                        <input id="datebr" type="date" class="col-12 form-control  form-control-lg"/>
                    </div>
                    <div class="col-12 row"  style="font-size: 200% !important; margin-top:20px;">
                        <div class="col-6" style="font-size: 100% !important;">
                            เพศ
                            <input id="gender" type="text" class="form-control  form-control-lg" placeholder="เพศ" aria-label="Username" aria-describedby="basic-addon1">
                        </div>
                        <div class="col-6"  style="font-size: 100% !important;">
                            อายุ
                            <input id="age" type="text" value="" class="form-control  form-control-lg" placeholder="อายุ" aria-label="Username" aria-describedby="basic-addon1">
                        </div>
                        เลขบัตรประชาชน
                        <input type="text" class="form-control  form-control-lg col-12" placeholder="เลขบัตรประชาชน" name="" id="cardno">
                        อาชีพ
                        <input type="text" class="form-control  form-control-lg col-12" placeholder="อาชีพ" name="" id="six">
                        สิทธิรักษา
                        <select class="form-control  form-control-lg" name="" id="careType">
                            <option value="1">ประกันสังคม</option>
                            <option value="2">ประกันสุขภาพ</option>
                            <option value="3">จ่ายเอง</option>
                            <option value="4">ข้าราชการ</option>
                            <option value="5">อื่นๆ...</option>
                        </select>
                        <div class="col-12 " id="caretypemorediv" style="display:none;">
                           <div>
                            <h4></h4>
                            </div>
                            <textarea class="form-control col-12" style="font-size: 1.3rem;" placeholder="ระบุสิทธิการรักษา" name="" id="caretypemore" cols="30" rows="3"></textarea>
                        </div>
                        โรคประจำตัว
                        <input type="text" placeholder="โรคประจำตัว" class=" form-control form-control-lg" id="pt_chronic" >
                        วันเวลาเจ็บหน้าอก
                        <div class="col-12 row">
                            <input id="pt_injurydatetime" type="date" class=" col-6 form-control form-control-lg pt_injurydatetime">
                            <input id="pt_injurydatetimetime" type="time" class="col-5 form-control form-control-lg" style="margin-left: 10px">
                        </div>
                        วันเวลารับผู้ป่วย
                        <div class="col-12 row">
                            <input id="pt_takedatetime" type="date" min="" class="col-6 form-control form-control-lg ">
                            <input id="pt_takedatetimetime" type="time" min="" class="col-5 form-control form-control-lg " style="margin-left:10px;">
                        </div>
                        วันเวลาทำ EKG
                        <div class="col-12 row">
                            <input id="pt_createekgtime" type="date" class="col-6 form-control form-control-lg">
                            <input id="pt_createekgtimetime" type="time" class="col-5 form-control form-control-lg" style="margin-left:10px;">

                        </div>
                        <div class="col-12" style="margin-top:20px;">
                            <button id="update_patient" class="btn btn-lg btn-success form-control">อัพเดทข้อมูล</button>
                        </div>
                    </div>


                    <div id="patient_id" value=""></div>
        </div>

            </div>
        </div>

        <div id="alert" class="alert alert-danger" style="display:none; font-size:25px; top: -360px;" role="alert">
            <h5 id="texttime"></h5>
          </div>

          <div id="alertsuccess" class="alert alert-danger" style="display:none; font-size:25px; top: -360px;" role="alert">
            <h5 id="texttime"></h5>
          </div>
    </div>

    <script src="{{URL::asset('public/assets/js/script.js')}}"></script>
    {{-- <script src="{{URL::asset('public')}}/stemi_css/datepicker/jquery.js"></script> --}}
    @include('patient.indexpatientmodal')
    <!-- การย้อนกลับรายการ -->
    @include('patient.indexreversestatussending')

    <script type="text/javascript">




      var sound = document.getElementById("myAudio");
      
      
    



        $(document).ready(function () {

            // $('#editpatient').modal('show');
            $('#datebr').change(function(){
                var y =new Date($(this).val())
                var today = new Date();
                var age = today.getFullYear() - y.getFullYear();
                $('#age').val(age)
                $('#age').html(age)

            })


            $('#pt_takedatetime').change(function(){
                // alert($('#pt_takedatetime').val())
                var date1 = new Date($('#pt_injurydatetime').val());
                var date2 = new Date($('#pt_takedatetime').val());
                var date3 = new Date($('#pt_createekgtime').val());
                var date11 = date2


                date3 = date3.getDate();
                var date2 =new Date(date2).getDate();

                var date1 = date1.getDate();
                var countdate12 =date2-date1;


                if(countdate12>=0){
                    $('#pt_injurydatetime').css('border-color','green')
                    $('#pt_takedatetime').css('border-color','green')
                    $('#alert').css('display','none')

                }else{
                    $('#pt_takedatetime').css('border-color','red')
                    $('#texttime').html("โปรดตรวจสอบเวลาต้องไม่น้อยกว่าวันที่"+'<br>'+$('#pt_injurydatetime').val())
                    $('#alert').css('display','block')
                }

            });



         
            // $('#pt_takedatetimetime').change(function(){

            //     var time1 =$('#pt_injurydatetimetime').val();
            //     // var time1 = time1.toTimeString();
            //     var time2 = new Date($('#pt_takedatetimetime').val());
            //     var time3= $('#pt_takedatetimetime').val()

            //     // var time3= new Date();
            //     // var time2 = time2.toTimeString();
            //     var counttime = $.diff(time3,time1);
            //     alert(counttime)
            //     // if($('#pt_takedatetimetime')val()>$('#pt_injurydatetimetime').val()){
            //     //     alert("ได้")
            //     // }else{
            //     //     alert("ไม่ได้")
            //     // }
            // })

            $('#pt_createekgtime').change(function(){
                var date1 = new Date($('#pt_injurydatetime').val());
                var date2 = new Date($('#pt_takedatetime').val());
                var date3 = new Date($('#pt_createekgtime').val());
                date3 = date3.getDate();
                var date2 =new Date(date2).getDate();
                var date1 = date1.getDate();
                var countdate12 =date2-date1;
                if(date3>=date2){

                    $(this).css('border-color','green')
                }else{
                    $(this).css('border-color','red')
                    $('#texttime').html("โปรดตรวจสอบเวลาต้องไม่น้อยกว่าวันที่"+'<br>'+$('#pt_takedatetime').val())
                    $('#alert').css('display','block')

                }
            })






            $('#modal_ekg').css("display","none");


            if("{!!isset($tab)!!}")
            {
               document.getElementById("{!!isset($tab)?$tab:''!!}").click();
            }

            $('#update_patient').click(function(){
                // var date1 = new Date($('#pt_injurydatetime').val());
                // var date2 = new Date($('#pt_takedatetime').val());
                // var date3 = new Date($('#pt_createekgtime').val());
                // // date3 = date3.getDate();
                // var date2 =new Date(date2).getDate();
                // var date1 = date1.getDate("yyyy/mm/dd");
                // var countdate12 =date2-date1;
             
                $.ajax({
                    type:'post',
                    headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url:'updateedit_patient',
                    dataType:'JSON',
                    data:{
                       
                        pt_id:$('#patient_id').attr('value'),
                        pt_name:$('#name').val(),
                        pt_dateofbirth:$('#datebr').val(),
                        pt_gender:$('#gender').val(),
                        pt_age: $('#age').val(),
                        pt_idcard:$('#cardno').val(),
                        pt_occupation:$('#six').val(),
                        pt_careType:$('#careType').val(),
                        pt_chronic:$('#pt_chronic').val(),
                        pt_careTypemore:$('#caretypemore').val(),
                        pt_injurydatetime:$('#pt_injurydatetime').val()+' '+$('#pt_injurydatetimetime').val(),
                        pt_takedatetime:$('#pt_takedatetime').val()+' '+$('#pt_takedatetimetime').val(),
                        pt_createekgtime:$('#pt_createekgtime').val()+' '+$('#pt_createekgtimetime').val(),

                    },
                    success: function(data){
                        $('#editpatient').modal('hide');
                    }
                    // Error: function(data){

                    // }

                })
            })
            $('.edit').click(function () {
                $id=$(this).attr('data');
                //  alert("คุณแน่ใจว่าจะลบข้อมูล");
                 jQuery('#loading').html(
                '<i class="fa fa-spinner fa-pulse  fa-fw" style="left: -40px; font-size: 75px;color:#ff0080; position: absolute;z-index: 9999;" id="load"></i>'
                );
                $.ajax({
                    type:'get',
                    url:'get_edititem',
                    dataType: 'json',
                    data:{
                        'id':$id
                    },
                    success: function (data) {
                        jQuery('#loading').css('display','none');
                        $('#caretypemorediv').css("display","none")
                // alert(data[0].pt_name);

                //  $('#data_patient').html(data.data);
                //  $('#editpatient').modal('show');
                        // window.location.href = "{{url('patient')}}";
                        console.log(data)
                $('#patient_id').attr('value',data[0].pt_id)
                $('#name').val(data[0].pt_name)
                $('#datebr').val(data[0].pt_dateofbirth)
                $('#gender').val(data[0].pt_gender)
                $('#age').val(data[0].pt_age)
                $('#cardno').val(data[0].pt_idcard)
                $('#six').val(data[0].pt_occupation)
                $("#careType").val(data[0].pt_caretype)
                if(data[0].pt_careTypemore != ""){
                    $('#caretypemorediv').css("display","block")
                }
                $("#caretypemore").val(data[0].pt_careTypemore)
                $('#patient_img').html(data[1])
                $('#editpatient').modal('show');
                $('#pt_chronic').val(data[0].pt_chronic);


                    }
                })
            });



            $('.patent_profile').click(function () {
                $('#profile_dis').html('');
                var pt_id = $(this).attr('id');

                $.ajax({
                    type: 'get',
                    url: '{{url("patient_profile")}}/' + pt_id + '',
                    dataType: 'json',
                    success: function (data) {
                        $('#profile_dis').html(data);
                    }
                });
                $('#profile_data').modal('show');
            });
        });

        function onClickCloseJob(id) {
            $("#patientclosejobid").val(id);
            $("#textareacancelmessage").val("");
            $('#patientclosejob').modal('show');
        }

        function clickUpdateSendPatientAlongWay(id) {
            if($('#textareacancelmessage').val()==""){
                alert("กรุณากรอกเหตุผล");
                $('#textareacancelmessage').css('border-color','red');
            }else{
                jQuery('#loading').html(
                '<i class="fa fa-spinner fa-pulse  fa-fw" style="font-size: 120px;color:#ccc; position: absolute;z-index: 9999;" id="load"></i>'
                );
                $pt_rq_refno=$('#action_dels').attr('data');
            $.ajax({
                type: 'post',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '{{url("update_sendalong")}}',
                dataType: 'json',
                data: {
                    pt_id: $("#patientclosejobid").val(),
                    reason: $("#textareacancelmessage").val(),
                    pt_rq_refno:$pt_rq_refno
                },
                success: function (result) {
                    console.log(result);
                    if (result.success) {
                        window.location.href = "{{url('patient')}}";
                    }
                }
            });
        }

        }

        $('select').change(function () {

            if($(this).val()==5){
                
                $('#caretypemorediv').css("display","block")
            }
            
  
        }); 

        function clickUpdateSendPatient(id) {
            jQuery('#loading').html(
                '<i class="fa fa-spinner fa-pulse  fa-fw" style="font-size: 120px;color:#ccc; position: absolute;z-index: 9999;" id="load"></i>'
                );
            $.ajax({
                type: 'post',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '{{url("update_send_patient")}}',
                dataType: 'json',
                data: {
                    pt_id: $("#patientclosejobid").val(),
                },
                success: function (result) {
                    console.log(result);
                    if (result.success) {
                        window.location.href = "{{url('patient')}}";
                    }
                }
            });
        }

        function onclickMap(id="",phone="") {
            try {
                    webkit.messageHandlers.onclickMap.postMessage(id+";"+phone);
            } catch(err) {
                    console.log(err);
            }

            try {
                    btnPatientMap.onclickMap(id,phone);
            } catch(err) {
                    console.log(err);
            }

        }

        function onclickMapHospital2() {
    
            try {
                    webkit.messageHandlers.onclickMapHospital.postMessage($('#patienttravelingid').val()+";"+ $('#patienttravelingphone').val() );
                } catch(err) {
                        console.log(err);
                }

                try {
                        btnHospitalMap.onclickMapHospital($('#patienttravelingid').val() ,$('#patienttravelingphone').val() );
                } catch(err) {
                        console.log(err);
                }

        }

        function onclickMapHospital(id, phone = "") {
          
            console.log("***********");
                try {
                        webkit.messageHandlers.onclickMap.postMessage(id+";"+ phone );
                } catch(err) {
                        console.log(err);
                }

                try {
                        btnHospitalMap.onclickMapHospital(id ,phone );
                } catch(err) {
                        console.log(err);
                }
        }

        function clickReverStatusModal(id) {


            $('#patientreversestatussendingclosejobmodal').modal({backdrop: 'static', keyboard: false});
            $("#patientreversestatussendingid").val(id);
        }


    function clickReverStatus() {
        jQuery('#loading').html(
                '<i class="fa fa-spinner fa-pulse  fa-fw" style="font-size: 120px;color:#ccc; position: absolute;z-index: 9999;" id="load"></i>'
                );
        $.ajax({
            type: 'post',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: '{{url("update_reverse_status")}}',
            dataType: 'json',
            data: {
                '_token': "{{ csrf_token() }}",
                pt_id: $('#patientreversestatussendingid').val(),
            },
            success: function (data) {

                window.location.href = "{{url('patient')}}";
                $('#patientreversestatussendingclosejobmodal').modal('hide');
            }

        });
    }

    $("#modal_close").click(function(){
        $('#modal_ekg').modal('hide');
    })

    $("#ekg_view").click(function(){

        $do = $('#ekg_view').attr("data_id");

        $.ajax({
            type: 'post',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: '{{url("ekg_view")}}',
            dataType: 'json',
            data: {
                '_token': "{{ csrf_token() }}",
                pt_id: $do,
            },
            success: function (data) {
         
                $("#ekg_pic").html(data.data);
                $("#modal_ekg").modal("show");
            }
        });




socket.on('amlsend',function(data){
           console.log(data)
           
        $idambulance=$('#selectshare').val();
        
        if(data.idambulance=$idambulance){
         
            $.ajax({
                url:'ambulan_schedule',
                type:'get',
                data:{
                    idambulance:$idambulance
                },
                success: function(data){
                    $('#u_0_v').css('display','none')
                    $('#amllist').html(data)
                    location.reload(true);
                }
            })
        }else{

        }

       })

    })
    </script>

    @endsection
